name: nectar_ui
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  provider: ^6.0.2
  # database
  shared_preferences: ^2.0.13
  # network
  vexana: ^3.0.1
  # core utilities
  kartal: ^2.4.0
  # ui utilities
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/svg/
    - assets/images/png/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 900