name: nectar_ui
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  provider: ^6.0.2

  # database
  shared_preferences: ^2.0.13
  firebase_storage: ^10.3.5
  cloud_firestore: ^3.4.4
  # network
  vexana: ^3.0.1

  # core utilities
  kartal: ^2.4.0

  # ui utilities
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2

  # authentication and user management
  firebase_core: ^1.20.1
  firebase_auth: ^3.6.3
  google_sign_in: ^5.4.1
  

  # localization 
  easy_localization: ^3.0.1
  # routing
  auto_route: ^4.2.1
  
  mobx_codegen: ^2.0.7
  badges: ^2.0.3
  carousel_slider: ^4.1.1
  dots_indicator: ^2.1.0
  image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  auto_route_generator: ^4.2.1
  build_runner: ^2.2.0
  dart_code_metrics: ^4.17.1
  
flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/lang/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 900